name: dotnet
'on':
  push:
    paths:
    - .github/workflows/sample1.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_DEPLOY_ENVIRONMENT: dev
      AZURE_RESOURCE_GROUP: rg-by-workflow-shared-dev-eus2-01
      AZURE_WEB_APP_TYPE: java
      AZURE_WEB_APP_NAME: alm-app-node-nodeappservice-dev
    steps:
    - uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: get endpoint url
      run: |
        queryout=$(az webapp config hostname list --webapp-name $AZURE_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --query [].name -o tsv)
        export hosturl="https://"$queryout

    - name: check file exist or not
      run: |
        if [ ! -f .github/webapps/webapps.json ]
        then
          mkdir -p .github/webapps
          touch .github/webapps/webapps.json
        cat >.github/webapps/webapps.json <<EOF
            {
              "$AZURE_WEB_APP_NAME": {
                 "resource_group": "$AZURE_DEPLOY_ENVIRONMENT",
                 "webapp_endpoint": "$hosturl"
              }
            }
        EOF
        cat .github/webapps/webapps.json
        git add .github/webapps/webapps.json
        git config --global user.email "dhanasekhar.podigiri@blueyonder.com"
        git config --global user.name "dhanasekhar podigiri"
        git commit .github/webapps/webapps.json -m "host name updated"
        git push
        fi
    - name: check application
      run:   echo ::set-output name=appout::$(grep "alm-app-node-nodeappservice-dev" .github/webapps/webapps.json | wc -l)
      id:    appgrep
      shell: bash
    - name: Run Project B
      if: steps.appgrep.outputs.appout == '0'
      run: |
        echo "empty"
        
  
