name: Create dotnet deploy
on:
  workflow_dispatch:
    inputs:
env:
  DOCKER_IMAGE_NAME: "alm-react-appservice-poc"
  AZURE_WEB_APP: "alm-react-appservice-poc"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        az group create --name dotnetcoredockerappservicedemo --location eastus
        az acr create --resource-group dotnetcoredockerappservicedemo --name frankContainerDemo01 --sku Basic --admin-enabled true
        az acr credential show -n frankContainerDemo01
        # docker build -t dotnetcoredockerappservicedemo .
        # docker tag dotnetcoredockerappservicedemo frankcontainerdemo01.azurecr.io/dotnetcoredockerappservicedemo:v1
        # docker login https://frankcontainerdemo01.azurecr.io -u frankContainerDemo01 -p <Password_Retreived>
        # docker push frankcontainerdemo01.azurecr.io/dotnetcoredockerappservicedemo:v1
        # az appservice plan create --name demoplan --resource-group dotnetcoredockerappservicedemo --sku S1 --is-linux
        # az webapp create -g dotnetcoredockerappservicedemo -p demoplan -n frankdockerdemo --runtime "DOTNETCORE|2.1"
        # az webapp config container set -n frankdockerdemo -g dotnetcoredockerappservicedemo --docker-custom-image-name frankcontainerdemo01.azurecr.io/dotnetcoredockerappservicedemo:v1 --docker-registry-server-url https://frankcontainerdemo01.azurecr.io --docker-registry-server-user frankContainerDemo01 --docker-registry-server-password <Password_Retreived> 
