name: dotnet
'on':
  push:
    paths:
    - .github/workflows/sample1.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_DEPLOY_ENVIRONMENT: dev
      AZURE_RESOURCE_GROUP: rg-by-workflow-shared-dev-eus2-01
      AZURE_WEB_APP_TYPE: java
      AZURE_WEB_APP_NAME: alm-app-node-nodeappservice-dev
    steps:
    - uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: endpoint url
      run: |
        echo "ENDPOINT_URL=https://$(az webapp config hostname list --webapp-name $AZURE_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --query [].name -o tsv)" >> $GITHUB_ENV

    - name: check file exist or not tes
      run: |
        if [ ! -f .github/webapps/webapps.json ]
        then
          mkdir -p .github/webapps
          touch .github/webapps/webapps.json
        cat >.github/webapps/webapps.json <<EOF
        {
           "$AZURE_WEB_APP_NAME":{
              "resource_group":"$AZURE_RESOURCE_GROUP",
              "webapp_endpoint":"$ENDPOINT_URL"
           }
        }
        EOF
        cat .github/webapps/webapps.json
        git add .github/webapps/webapps.json
        git config --global user.email "dhanasekhar.podigiri@blueyonder.com"
        git config --global user.name "dhanasekhar podigiri"
        git commit .github/webapps/webapps.json -m "host name updated"
        git push
        fi
    - name: check application
      run:   echo ::set-output name=appout::$(grep "$AZURE_WEB_APP_NAME" .github/webapps/webapps.json | wc -l)
      id:    appgrep
      shell: bash
    - name: update endpoint with json
      if: steps.appgrep.outputs.appout == '0'
      run: |
        sed -i '$d' .github/webapps/webapps.json | sed '$d' | sed '$d'
        sed -i '$d' .github/webapps/webapps.json | sed '$d' | sed '$d'
        cat >>.github/webapps/webapps.json <<EOF
           },
           "$AZURE_WEB_APP_NAME": {
              "resource_group": "$AZURE_RESOURCE_GROUP",
              "webapp_endpoint": "$ENDPOINT_URL"
           }
        }
        EOF
        cat .github/webapps/webapps.json
        git add .github/webapps/webapps.json
        git config --global user.email "dhanasekhar.podigiri@blueyonder.com"
        git config --global user.name "dhanasekhar podigiri"
        git commit .github/webapps/webapps.json -m "host name updated"
        git push
    - name: check 
      run: |
        echo "$(jq '."${{ env.AZURE_WEB_APP_NAME }}"'.webapp_endpoint .github/webapps/webapps.json)" >> temp.txt
        temp=`cat temp.txt`
        temp=`echo $temp | sed "s/\"//g"`
        echo $temp
        echo $ENDPOINT_URL
        if [[ "$temp" != "$ENDPOINT_URL" ]]
        then
        echo "inside if"
        jq '."${{ env.AZURE_WEB_APP_NAME }}".webapp_endpoint="${{ env.ENDPOINT_URL }}"' .github/webapps/webapps.json
         git add .github/webapps/webapps.json
        git config --global user.email "dhanasekhar.podigiri@blueyonder.com"
        git config --global user.name "dhanasekhar podigiri"
        git commit .github/webapps/webapps.json -m "host name updated"
        git push
        cat .github/webapps/webapps.json
        fi
