name: dotnet
'on':
  push:
    paths:
    - .github/workflows/sample1.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_DEPLOY_ENVIRONMENT: dev
      AZURE_RESOURCE_GROUP: rg-by-workflow-shared-dev-eus2-01
      AZURE_WEB_APP_TYPE: java
      AZURE_WEB_APP_NAME: alm-app-node-nodeappservice-dev
    steps:
    - uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: endpoint url
      run: |
        queryout=$(az webapp config hostname list --webapp-name $AZURE_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --query [].name -o tsv)
        ENDPOINT="https://"$queryout
        echo $queryout
        echo $ENDPOINT
        echo 'ENDPOINT_URL="https://"$(az webapp config hostname list --webapp-name $AZURE_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --query [].name -o tsv)' >> $GITHUB_ENV

    - name: output var
      run:   echo ::set-output name=appou::"https://"$(az webapp config hostname list --webapp-name $AZURE_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --query [].name -o tsv)
      id:    appgrep
      shell: bash
    - name: ooo
      run: |
        echo "${{ steps.appgrep.outputs.appou }}"
        echo $ENDPOINT_URL
        echo ${{ env.ENDPOINT_URL }}
        
