name: dotnet
'on':
  push:
    paths:
    - .github/workflows/sample1.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_DEPLOY_ENVIRONMENT: dev
      AZURE_RESOURCE_GROUP: rg-by-workflow-shared-dev-eus2-01
      AZURE_WEB_APP_TYPE: java
    steps:
    - uses: actions/checkout@v2
    - name: get url
      run: |
        if [ ! -f .github/webapps/webapps.json ]
        then
          mkdir -p .github/webapps/webapps.json
          echo "created new file"
        fi
    - uses: "actions/setup-python@v2"
      with:
        python-version: "3.9"
    - name: "Import package"
      run: "python -c 'import json'"
      
    - name: "Parse json"
      run: |
        person_dict = json.loads(.github/webapps/webapps.json)
        print( person_dict)
