name: stest
'on':
  push:
    paths:
    - .github/workflows/sample3.yaml
jobs:
  create-web-app:      
    runs-on: ubuntu-latest
    env:
      AZURE_DEPLOY_ENVIRONMENT: dev
      AZURE_RESOURCE_GROUP: rg-by-workflow-shared-dev-eus2-01
      AZURE_WEB_APP_TYPE: java
      AZURE_WEB_APP_NAME: alm-app-java-javaappservice-dev
      AZURE_WEB_APP_NAME_PREFIX: 'alm-app'
      AZURE_WEB_APP_SKU: 'S1'
      AZURE_WEB_APP_WORKERS: '4'
      AZURE_ACR_NAME_PREFIX: 'almacr'
      AZURE_ACR_SKU: 'Standard'
      AZURE_ACR_ADMIN_ENABLED: true
    steps:
    - uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Update Azure Web App Endpoints File
      run: |
        if [ ! -f .github/webapps/webapps.json ];then
          mkdir -p .github/webapps
          touch .github/webapps/webapps.json
        fi
        export WEB_APP_URL=`az webapp config hostname list --webapp-name $AZURE_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --query [].name -o tsv`
        jq --arg webapp_name $AZURE_WEB_APP_NAME --arg resource_group $AZURE_RESOURCE_GROUP --arg webapp_url "https://$WEB_APP_URL" '. + {($webapp_name): {"resource_group": $resource_group, "webapp_url": $webapp_url}}' < .github/webapps/webapps.json > tmp_webapps.json && cp tmp_webapps.json .github/webapps/webapps.json
        cat tmp_webapps.json
        git config --global user.email "siva.medapati@blueyonder.com"
        git config --global user.name "Siva Medapati"
        git config pull.rebase false
        git pull origin ${BRANCH}
        git add -f .github/webapps/webapps.json
        if [ -z "$(git status --porcelain)" ]; then 
          echo "Nothing to commit "
        else 
          git commit -m "update webapp endpoin"
          git push origin ${BRANCH}
        fi
