name: dotnet
'on':
  push:
    paths:
    - .github/workflows/sample.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_DEPLOY_ENVIRONMENT: dev
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: get url
      run: |
        out=$(az webapp list --query "[?name=='alm-app-java-devlopmentpoc-d']")
        if [[ -n $(echo $out | sed 's/\(\[\|\]\)//g') ]]; then
        echo "non empty"
        else
        echo "empty"
        fi
