name: strato
'on':
  push:
    paths:
    - .github/workflows/strato.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRATOSPHERE_WEB_APP_NAME_PREFIX : alm-app
      AZURE_WEB_APP_TYPE: java
      GITHUB_REPO_NAME: javaappservice
      STRATOSPHERE_DEPLOY_ENVIRONMENT: dev
      AZURE_ACR_NAME_PREFIX: almacr
      CONTAINER_REGISTRY_NAME: almacrdev
      AZURE_WEB_APP_IMAGE_NAME: javaappservice-dev
      STRATOSPHERE_API_URL : https://api.live.external.byp.ai
      PROJECT_NAME: alm
      REGION: us
      AZURE_WEB_APP_NAME: alm-ap-devp
      owner_group_name : grp-sec-saas-sub-lplat-test-reader
      PYTHON_VERSION: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${<!-- -->{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${<!-- -->{ env.PYTHON_VERSION }}
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
