name: strato
'on':
  push:
    paths:
    - .github/workflows/strato.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRATOSPHERE_WEB_APP_NAME_PREFIX : alm-app
      AZURE_WEB_APP_TYPE: java
      GITHUB_REPO_NAME: javaappservice
      STRATOSPHERE_DEPLOY_ENVIRONMENT: dev
      AZURE_ACR_NAME_PREFIX: almacr
      CONTAINER_REGISTRY_NAME: almacrdev
      AZURE_WEB_APP_IMAGE_NAME: javaappservice-dev
      STRATOSPHERE_API_URL : https://api.live.external.byp.ai
      PROJECT_NAME: alm
      REGION: us
      AZURE_WEB_APP_NAME: alm-app-java-a
      OWNER_GROUP_NAME : 'grp-sec-saas-sub-lplat-test-reader'
    steps:
    - uses: actions/checkout@v2
    - name: create container registry
      run: |
        curl -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.ST_TOKEN }}" \
          --request PUT \
          --data '{"spec": {
                     "container_registry": {
                     "access_policies": [{"name": "grp-sec-saas-sub-lplat-test-reader", "type": "group"}]}
                     }
                  }' \
          ${{ env.STRATOSPHERE_API_URL }}/geographies/${{ env.REGION }}/projects/${{ env.PROJECT_NAME }}/resources/azure-container-registry/${{ env.CONTAINER_REGISTRY_NAME }}
