name: strato
'on':
  push:
    paths:
    - .github/workflows/strato.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRATOSPHERE_WEB_APP_NAME_PREFIX : alm-app
      AZURE_WEB_APP_TYPE: java
      GITHUB_REPO_NAME: javaappservice
      STRATOSPHERE_DEPLOY_ENVIRONMENT: dev
      AZURE_ACR_NAME_PREFIX: almacr
      CONTAINER_REGISTRY_NAME: almacrdev
      AZURE_WEB_APP_IMAGE_NAME: javaappservice-dev
      STRATOSPHERE_API_URL : https://api.live.external.byp.ai
      PROJECT_NAME: alm
      REGION: us
      AZURE_WEB_APP_NAME: alm-ap-devp
      owner_group_name : grp-sec-saas-sub-lplat-test-reader
      ST_TOKEN: ${{ secrets.ST_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: invoke curl
      run: |
        curl -X GET "${{ env.STRATOSPHERE_API_URL }}/geographies/$REGION/projects/$PROJECT_NAME/resources/container-web/alm-app-java" -H  "accept: application/json" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ1SDVhUWNsd0lPR2RJb1lhQXh5Q0VyVDM2MjZoa2M4MTRIdDB0c1lDbzBNIn0.eyJleHAiOjE2MjEzNTQ5NDgsImlhdCI6MTYyMTMyNjE0OCwianRpIjoiZTg2YjQwNGQtZmJiMC00NGFiLWJkNmItYWFlYTY5OGYzNzk3IiwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5saXZlLmV4dGVybmFsLmJ5cC5haS9yZWFsbXMvU3RyYXRvc3BoZXJlIiwiYXVkIjpbInN0cmF0b3NwaGVyZS1hbG0iLCJpYXAiLCJhY2NvdW50Il0sInN1YiI6IjlmMzFhOGY1LTBhNzUtNDU1Yy1hOTMzLTJhZmRiMWRiMmIwMiIsInR5cCI6IkJlYXJlciIsImF6cCI6InN0cmF0b3NwaGVyZS1hbG0iLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MSJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImNsaWVudElkIjoic3RyYXRvc3BoZXJlLWFsbSIsImNsaWVudEhvc3QiOiIxOTIuMTg5LjgzLjE0IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtc3RyYXRvc3BoZXJlLWFsbSIsImNsaWVudEFkZHJlc3MiOiIxOTIuMTg5LjgzLjE0In0.dVr3aCix63bhHN3cWz1V_anydu_eiofBWe5TFfRmQfy7qZwUx3JL30FRYBj2RN1HkrS51R8TcU4hLapVrmFup3MoVT9vas_ZqvWPzR8J_01WPX1L1o04twUUdlVJFxz69HsmrBnOzw9RLMqxpLYODr5YySMPafLr-TgaUQg7Si5iMhLvk_DfbHSDDxMY0NTo2atriaaQ01IpezCX1UkvJtnx677iu8N32MtaCKgb1fVMkF_xmGcNm4XpBcOSymYhyOqN1ncRnqNFsMVrmzIqvYsO2nwbFZTioH-zbDtQD4ZaXpaIc-4SvDL5K1kCJog3oZtGaJY2SOWIBOUWGo9v5w"
