name: Deploy Azure Web App 
on:
  repository_dispatch:
    types: app_service_deploy
jobs:
  deploy-web-app:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO_NAME: "${{ github.event.client_payload.repo }}"
      AZURE_SUBSCRIPTION: "${{ github.event.client_payload.subscription }}"
      AZURE_RESOURCE_GROUP: "${{ github.event.client_payload.resource_group }}"
      AZURE_DEPLOY_ENVIRONMENT: "${{ github.event.client_payload.environment }}"
      AZURE_WEB_APP_TYPE: "react"
      AZURE_WEB_APP_NAME_PREFIX: 'alm-app'
      AZURE_ACR_NAME_PREFIX: 'almacr'
      AZURE_ACR_ADMIN_ENABLED: true
      AZURE_WEB_APP_NAME: 'alm-app-react-almrepo-dev'
    steps:
    - name: Set env
      run: |
        echo "AZURE_WEB_APP_NAME_PREFIX1=${AZURE_WEB_APP_NAME_PREFIX}-${AZURE_WEB_APP_TYPE}" >> $GITHUB_ENV
        echo "AZURE_WEB_APP_NAME1=${AZURE_WEB_APP_NAME_PREFIX1}-${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_ACR_NAME=${AZURE_ACR_NAME_PREFIX}${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        echo "AZURE_WEB_APP_IMAGE_NAME=${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
        
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Timestamp
      id: time
      run: |
        echo "AZURE_WEB_APP_IMAGE_TAG=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
            
    - name: Build Docker Image
      run: |
        docker build . --file ".github/docker/Dockerfile_$AZURE_WEB_APP_TYPE" --tag "$AZURE_ACR_NAME.azurecr.io/$AZURE_WEB_APP_IMAGE_NAME:$AZURE_WEB_APP_IMAGE_TAG"
        
    - name: Tag Docker Image
      run: |
        docker tag $AZURE_ACR_NAME.azurecr.io/$AZURE_WEB_APP_IMAGE_NAME:$AZURE_WEB_APP_IMAGE_TAG $AZURE_ACR_NAME.azurecr.io/$AZURE_WEB_APP_IMAGE_NAME:latest
        
    - name: Login to ACR
      run: |
        REGISTRY_PASSWORD=$(az acr credential show -n $AZURE_ACR_NAME --query "passwords[0].value"  -o tsv)
        echo $REGISTRY_PASSWORD | docker login almacrdev.azurecr.io --username $AZURE_ACR_NAME --password-stdin

    - name: Push Docker Images
      run: |
        docker push "$AZURE_ACR_NAME.azurecr.io/$AZURE_WEB_APP_IMAGE_NAME:$AZURE_WEB_APP_IMAGE_TAG"
        docker push "$AZURE_ACR_NAME.azurecr.io/$AZURE_WEB_APP_IMAGE_NAME:latest"
        
    - name: Update Web App Container Settings
      run: | 
        az webapp config container set --name ${{ env.AZURE_WEB_APP_NAME }} \
        --resource-group $AZURE_RESOURCE_GROUP \
        --docker-custom-image-name "$AZURE_ACR_NAME.azure.io/$AZURE_WEB_APP_IMAGE_NAME:latest" \
        --docker-registry-server-url "https://$AZURE_ACR_NAME.azurecr.io" \
        --docker-registry-server-user $AZURE_ACR_NAME \
        --docker-registry-server-password "veh65IFApm=u0KSqAkygQ6WHigjbVNYw"
