name: Azure WebApp Container Deployment
true:
  repository_dispatch:
    types: deployApp
env:
  AZURE_WEB_APP: ${{ github.event.client_payload.webapp_name }}
  DOCKER_IMAGE_NAME: ${{ github.event.client_payload.docker_image_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
    - name: List Docker images
      run: docker images
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER}}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        username: ${{ secrets.REGISTRY_USERNAME }}
    - name: Tag the Docker image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}':latest '${{secrets.REGISTRY_LOGIN_SERVER}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Push the Docker image
      run: docker push '${{secrets.REGISTRY_LOGIN_SERVER}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEB_APP }}
        app-settings-json: "[\n    {\n        \"name\": \"DOCKER_REGISTRY_SERVER_PASSWORD\"\
          ,\n        \"value\": \"${{ secrets.REGISTRY_PASSWORD }}\",\n        \"\
          slotSetting\": false\n    },\n    {\n        \"name\": \"DOCKER_REGISTRY_SERVER_URL\"\
          ,\n        \"value\": \"https://${{ secrets.REGISTRY_LOGIN_SERVER }}\",\n\
          \        \"slotSetting\": false\n    },\n    {\n        \"name\": \"DOCKER_REGISTRY_SERVER_USERNAME\"\
          ,\n        \"value\": \"${{ secrets.REGISTRY_USERNAME  }}\",\n        \"\
          slotSetting\": false\n    }\n]  \n"
    - name: Azure WebApp Deployment
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEB_APP}}
        images: ${{secrets.REGISTRY_LOGIN_SERVER}}/${{env.DOCKER_IMAGE_NAME}}:latest
